### ISSUE TITLE
Order of rules seems to be randomly changed

### ISSUE THREAD

**Issue by kliegr** [KIZI/EasyMiner-BRE#6]
It seems that the editor (or some related functionality) changes the order of rules on the output randomly. 

The default rule in the "mined" export is sometimes listed as first as opposed to the expected last position.
In the modified export, the position of the rule changed again.  See attachment 9A
[9A.tar.gz](https://github.com/KIZI/EasyMiner-BRE/files/2487319/9A.tar.gz)
[16B.tar.gz](https://github.com/KIZI/EasyMiner-BRE/files/2487320/16B.tar.gz)

The change in position also seems to affect sometimes the first and last rule, even if it is not a default rule. In attachment 16B, the first rule in the mined export, becomes second last rule in the modified export.

**Comment by vojir** [comment]
The rules in export are not ordered. The model tester determines the order of rules using its interest measures.

**Comment by vojir** [comment]
By default, rules are now sorted by confidence. But it is possible to select another sorting method using parametr *order* in URL. Supported values are *confidence*, *support*, *antecedent_rule_attributes*, *cba*.

For example, the export URL could be:
_https://{server}/easyminercenter/em/rule-sets/text/{rule set ID}?order=cba_
